# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: kube-system
stringData:
    email: ENC[AES256_GCM,data:6gogTaPyM3z3AmxybA==,iv:1b2KJszGwoRoXa3IXEri9qZCziRGTId6juvk8qEdCqI=,tag:Y98MT8bvi2etVKO5iuhxZg==,type:str]
    api-key: ENC[AES256_GCM,data:Q5/suoneabmJfbXqnOsRRkP5ig471oIIecmJojsj78c4pe4o+Q==,iv:kIM584Yi0NZUUwt1iE29/xSlTlsplYV8y2+jhaO/w6U=,tag:TdbIJwZTh1J4dh/MAcJpSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rhc7lprjfcfl2uyjxcc0nny7h0ha0l7uykvah0vmcf2s7hecp94qupxyym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMlNiTkpmS2FxQklKc0pS
            RmlXN3FVVVU4VHhxQmt6YjJZTUJ0MWNpeFVBCnozK1F2NVlZc283ZXg2Vk5yWkk5
            Tm9vc0lkODBHZnNOZElCT0wrQkdJWjAKLS0tIEZKOFg3MnRjaHVBSC9UcGFtNlAy
            dVRqZDF2S3JtTHNMMHJRNTFRYTNySWsKnj/NtGCjIrGyecuuOi8oG7kltxgIho/0
            qa2DXTHYYY76TDbCz65Oqw0KK+7cTg1M1TfRfMke8cv5WHbvjvlcGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T19:43:26Z"
    mac: ENC[AES256_GCM,data:begnqRaLMg6m7wgiu3lMvoyHqzfMlWZRkMwSTGDbGe1DXudbNkvHrrsaKjy/DSjVW03Stgx7u1Az/qtifCX2vZCZEb1EzP6KBGO1/30DcXCXS1iumV1sPQvw+bopEKipLXKMHjKzN3ZZ8PNyDgf+XzaI54LmIsqwO0BYvj5WZcA=,iv:dJaKMMJxT2GE6MEsrRXubbQNXnHxdm+LNl6OyuURZaI=,tag:HuUFAcZkmtt1IJ7S4sC2fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
