---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 10.28.1.70-10.28.1.79
  METALLB_K8S_GATEWAY_ADDR: 10.28.1.78
  METALLB_INGRESS_ADDR: 10.28.1.79
